Develop
isthatkirill/java-filmorate pull request #24
Opened 2023-05-28 21:07 UTC by isthatkirill

2023-05-29 21:20 UTC, z8q requested changes
Хорошая работа!
Большинство ошибочных запросов обрабатывается и возвращаются понятные сообщения.
Хорошо реализована логика, поддерживать код будет возможно)
В коде оставил комментарии по доработкам

2023-05-29 21:20 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    @SaveUserFeed(
Интересное решение

2023-05-29 21:20 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            } else {
Много if-ов
На собесах могут спрашивать, как конструкции if/else и switch нарушают open-closed принцип в SOLID.
Тут
https://www.freecodecamp.org/news/open-closed-principle-solid-architecture-concept-explained/
и
тут
https://proglib.io/p/udalite-iz-koda-if-else-i-switch-case-2021-06-02
Можно посмотреть, как избегать.

Просто для информации)

2023-05-29 21:20 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    public List<Film> getRecommendations(@PathVariable Long id) {
Работает)

2023-05-29 21:20 UTC, z8q commented on pom.xml
>  		</dependency>
В файле readme стоит добавит описание того, какие задачи выполнила группа.

2023-05-30 14:29 UTC, Holy-Raven commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (directors != null && !directors.isEmpty()) {
исправила.

2023-05-31 19:28 UTC, Holy-Raven submitted a review, later dismissed

2023-05-31 20:48 UTC, z8q approved these changes

2023-05-31 20:48 UTC, z8q approved these changes

2023-06-01 18:09 UTC, merged